language: c++

os:
  - linux

env:
  matrix:
      - RPCLIB_CXX_STANDARD=14 BUILD_TYPE=Release
      - RPCLIB_CXX_STANDARD=11 BUILD_TYPE=Release

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - libsfml-dev
      - g++-5
      - gcc-5
      - clang-3.8
      - cmake
      - cmake-data

install:
  - if [ "$CXX" == "g++" ];     then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
  - pip install --user cpp-coveralls
  - pip install --user conan
  - pip install --user requests==2.5.3
  - conan remote add conan-community https://api.bintray.com/conan/conan-community/conan

script:
  - mkdir build ; cd build
  - conan install .. -r conan-community
  - . ./activate.sh
  - cmake -DRPCLIB_ENABLE_COVERAGE=ON -DRPCLIB_BUILD_TESTS=ON -DRPCLIB_CXX_STANDARD=$RPCLIB_CXX_STANDARD -DCMAKE_INSTALL_PREFIX=../install ..
  - cmake --build . --config $BUILD_TYPE
  - cmake --build . --target install

after_success:
  - ./output/bin/rpc_test
  - coveralls --exclude dependencies --exclude test --exclude include/rpc/msgpack --exclude include/rcp/msgpack.hpp --gcov /usr/bin/gcov-5
